name: Build, Push Docker Image, and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:  # 주석 처리된 build_push 작업과 구분
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # SSH 키에 적절한 권한 설정

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_EC2_IP }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy with Podman
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
            sudo podman pull ${{ secrets.DOCKER_USERNAME }}/springtest:latest
            sudo podman ps -q --filter "name=springtest" | xargs -I {} sudo podman stop {}
            sudo podman ps -a -q --filter "name=springtest" | xargs -I {} sudo podman rm {}
            sudo podman run -d --name springtest -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/springtest:latest
          EOF
